apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-ml
  template:
    metadata:
      labels:
        app: vulnerable-ml
    spec:
      containers:
      - name: ml-container
        image: vulnerable-ml:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-ml-service
  annotations:
    cloud.google.com/load-balancer-type: "External"  # Optional for clarity
spec:
  type: LoadBalancer
  selector:
    app: vulnerable-ml
  ports:
  - protocol: TCP
    port: 80            # External port
    targetPort: 5000    # Container port
